services:
  mongo:
    image: mongo
    restart: always
    networks:
      - my-networks
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=library
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - my-networks
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Asdfg123
  counter:
    image: count
    container_name: counter
    networks:
      - my-networks
    ports:
      - 5001:5001
    environment:
      - PORT_COUNTER=5001
  library:
    image: lib
    container_name: library
    networks:
      - my-networks
    ports:
      - 80:3001
    environment:
      - PORT=3001
      - COUNTER_URL=http://counter:5001
      - UrlDB=mongodb://mongo/library
    depends_on:
      - counter
networks:
  my-networks:
    name: my-networks
    driver: bridge

