services:
  counter:
    build:
      context: counter
      dockerfile: Dockerfile
    container_name: counter
    networks:
      - my-networks
    ports:
      - 5001:5001
    volumes:
      - ./counter/data/:/app/data/
    environment:
      - PORT_COUNTER=5001
  library:
    image: vikkelas/library
    container_name: library
    networks:
      - my-networks
    ports:
      - 80:3001
    environment:
      - PORT=3001
      - COUNTER_URL=http://counter:5001
    depends_on:
      - counter
networks:
  my-networks:
    name: my-networks
    driver: bridge

